aswo_dashboard:
    resource: "@AswoDashboardBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login:
    path:   /Login
    defaults:  { _controller: AswoUserBundle:Security:login }

login_check:
    path:   /Login_check

logout:
    path:   /Logout