aswo_user:
    resource: "@AswoUserBundle/Resources/config/routing.yml"
    prefix:   /

aswo_dashboard:
    resource: "@AswoDashboardBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login:
    pattern:   /login
    defaults:  { _controller: AswoUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout